language: node_js
node_js:
  - '6'

cache:
  yarn: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.pip/cache"
    - "$HOME/.yarn-cache"

script:
 - npm run lint --max-warnings=0

deploy:
  - provider: npm
    email: "paulius.jarmalavicius@gmail.com"
    api_key:
      secure: fIpuOhuU6P1EHjnU9DvliaBEmm7ePyJlAPUL/K7EUhiLaGptzz3e06k6XgAQ9mJtu8vZdJDbiMECxWIjm7tzQNyOnr5+ITl0POzphtNna3NcbkENcBA1nRIgQpRwDZje9xu4DNsTucf94QYD1W/1KishTYiSukdB2/3/kEgjhg2KSGyyPHseFzPIqmcWwGpzdeY+OHpwkA2R65gZ3vQUiWDeYu1Q1UT7TQeGgGv570F6PqQxnQXibYvJOfBdTawmDXTnU7Tn5csaod5p43KpkNBmdzchNAnpTOvZj4gbbYfykFz9o8yxQ3tAmrs4lJH/+Rn0EvHxMvOUbCdgFIMnCeFWUM3GoNT/2LVX+Ltjfn8I9uXDSbf524FjStrKUGX/cAabQS6waqJl6/doPxahfWK9MB3vNV5vWCa706U89c3z1ZT4cIPM27zAEKnRGHu1awqPvL0+ClvJ1g2K9AkJTnChjmCKyoCLYJF/YBYnbOMdIqfmH/3dkFyyUkkxWqSUfSz0PiNFNcZZG5q3DqBYt0jGtTAmyIHYoj2ARYHJncIpo+gE5cT8MSa7yHlZh5/2ZaegQYoC+hVX9LBIxGOx3MaGd2BoFQ84glhQep1+E5imrx+LmwEZuX/pllMQaJA5obq5inwUG8JtBI569JVYKk2vR7q0slG2BkKvbTlNy90=
    on:
      tags: true
